//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sedas_Ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stoklar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stoklar()
        {
            this.Carilers = new HashSet<Cariler>();
        }
    
        public int StokID { get; set; }
        public string StokAdi { get; set; }
        public string StokKodu { get; set; }
        public string OlcuBirimi { get; set; }
        public string GrupAdi { get; set; }
        public string KDV { get; set; }
        public string BirimFiyati { get; set; }
        public string GirisMiktari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cariler> Carilers { get; set; }
    }
}
